name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint and check score
        run: |
          # Run pylint and extract the score
          SCORE=$(pylint demo.py | tee pylint-output.txt | tail -n 2 | grep -oE "[0-9]+\.[0-9]+(?=/10)")
          
          echo "Pylint score is: $SCORE"

          # Compare the score with threshold
          THRESHOLD=5.0
          RESULT=$(echo "$SCORE > $THRESHOLD" | bc)

          if [ "$RESULT" -eq 1 ]; then
            echo "✅ Pylint score is above $THRESHOLD. Proceeding..."
          else
            echo "❌ Pylint score is $SCORE, which is not acceptable (min required: $THRESHOLD)."
            exit 1
          fi
